version: '3'
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy 
    ports:
      - "4180:4180"
    environment:
      - OAUTH2_PROXY_CONFIG=/config/oauth2_proxy.cfg
    volumes:
      - ./oauth2_proxy.cfg:/config/oauth2_proxy.cfg:ro

  my-rust-app:
    image: my-rust-app-image
    ports:
      - "8000:8000"

